before_script:
  - apt-get update
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - test

stockmono_build:
  image: ubuntu:18.04
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp
    - mono --version

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

stockmono_test:
  image: ubuntu:18.04
  stage: test
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp

    - time (apt-get install -y nunit-console &&
            ./configure.sh &&
            make &&
            make check)

stocknewmono_build:
  image: ubuntu:19.04
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp
    - mono --version

    # compilation fails due to this bug: https://github.com/fsharp/fsharp/issues/740
    #- time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    #- make nuget

newmono_build:
  image: ubuntu:18.04
  stage: build
  artifacts:
    paths:
      - bin/*.zip
    expire_in: 1 week
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    # NOTE: this is needed as a workaround to this bug: https://github.com/mono/mono/issues/10570
    - ./scripts/install_dotnet_sdk_from_microsoft_deb_packages.sh

    # so that it builds the GTK frontend
    - apt install -y libgtk2.0-cil-dev

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

    - apt-get install -y zip
    - make zip

newmono_test:
  image: ubuntu:18.04
  stage: test
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - apt install -y nunit-console

    - time (./configure.sh && make && make check)
