before_script:
  - apt-get update
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - unit_tests
  - integration_tests
  - package

stockmono_build:
  image: ubuntu:18.04
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y mono-complete mono-xbuild fsharp
    - mono --version

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

stockmono_test_unit:
  image: ubuntu:18.04
  stage: unit_tests
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y mono-complete mono-xbuild fsharp

    - time (apt-get install -y nunit-console &&
            ./configure.sh &&
            make &&
            make check)

stocknewmono_build:
  image: ubuntu:19.04
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y mono-complete mono-xbuild fsharp
    - mono --version

    # fsharpi is broken in Ubuntu 19.04 ( https://github.com/fsharp/fsharp/issues/740 ) so
    # we can install 'fsx' as a workaorund
    - apt install -y git && git clone https://gitlab.com/knocte/fsx.git
    - cd fsx && ./configure.sh && make install && cd ..

    - ./configure.sh
    # FIXME: compilation fails for now due to some Nuget's bug:https://github.com/NuGet/Home/issues/7202

newmono_build:
  image: ubuntu:18.04
  stage: build
  artifacts:
    paths:
      - bin/*.zip
    expire_in: 50days
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    # NOTE: this is needed as a workaround to this bug: https://github.com/mono/mono/issues/10570
    - ./scripts/install_dotnet_sdk_from_microsoft_deb_packages.sh

    # so that it builds the GTK frontend
    - apt install -y libgtk2.0-cil-dev

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

    - apt-get install -y zip
    - make zip

newmono_test_unit:
  image: ubuntu:18.04
  stage: unit_tests
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - apt install -y nunit-console

    - time (./configure.sh && make && make check)

stockmono_test_integration:
  image: ubuntu:18.04
  stage: integration_tests
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y mono-complete mono-xbuild fsharp

    - ./configure.sh &&
      make &&
      make update-servers

newmono_test_integration:
  image: ubuntu:18.04
  stage: integration_tests
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - ./configure.sh &&
      make &&
      make update-servers

# snap package generation is not working with GitLabCI; TODO: report bug
#stockmono_package:
#  image: ubuntu:18.04
#  stage: package
#  script:
#    - ./scripts/install_mono_from_microsoft_deb_packages.sh
#
#    - apt install -y sudo
#    - ./scripts/install_snapcraft_dockerless.sh
#    # finish installation of snapcraft
#    - export SNAP=/snap/snapcraft/current
#    - export SNAP_NAME=snapcraft
#    - export SNAP_ARCH=amd64
#    - export PATH="/snap/bin:$PATH"
#
#    - /snap/bin/snapcraft --version
#
#    - ./scripts/snap_build.sh
#
#  artifacts:
#    paths:
#      - gwallet*.snap
#    expire_in: 50days
