name: macOS

on: [push]

jobs:
  macOS_build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ./configure.sh && make strict && make sanitycheck && make release

  macOS_tests_unit:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ./configure.sh && make && make check

  macOS_tests_integration:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ./configure.sh && make && make update-servers
